//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Database.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DATABATYPE                  129
#define IDB_BITMAP_BG                   130
#define IDR_MENU1                       131
#define IDI_ICON1                       132
#define IDB_BITMAP_LOGIN                133
#define IDD_DIALOG_LOGIN                134
#define IDD_DIALOG_USERSETTING          135
#define IDD_DIALOG_COMMON               136
#define IDD_DIALOG_NATIONINFORMATION    137
#define IDD_DIALOG_POSITIONINFORMATION  138
#define IDD_DIALOG_EDUCATIONDEGREE      139
#define IDD_DIALOG_POLITICALSTATUS      140
#define IDD_DIALOG_DEPARTMENTSECTION    141
#define IDD_DIALOG_WAGELEVEL            142
#define IDD_DIALOG_TECHNICALPOST        143
#define IDD_DIALOG_ADMINISTRATIVEPOST   144
#define IDD_DIALOG_DEPARTMENT           145
#define IDD_DIALOG_SECTION              147
#define IDD_DIALOG_AUXILIARY            149
#define IDD_DIALOG_APPENDANT            151
#define IDD_DIALOG_FULLTIME             153
#define IDD_HUMAN_HBASEARCHIVE          155
#define IDD_DIALOG_HFAMILYMEMBER        157
#define IDD_DIALOG_HWORKEXPERIENCE      159
#define IDD_DIALOG_HREWARDRECORD        161
#define IDD_DIALOG_HDISCIPLINEPUNISH    163
#define IDD_DIALOG_HPAPER               165
#define IDD_DIALOG_HPROJECT             167
#define IDD_DIALOG_HTECHNICALACCESS     169
#define IDD_DIALOG_HACADEMICEDUCATION   171
#define IDD_DIALOG_HCONTINUEEDUCATION   173
#define IDD_DIALOG_HCLASSTEACHING       175
#define IDD_DIALOG_BROWSE               177
#define IDD_DIALOG_HSEARCH              179
#define IDD_DIALOG_HSTATISTICS          181
#define IDD_DIALOG_NOTES                182
#define IDD_DIALOG_COMMUNICATIONTHIN    184
#define IDD_DIALOG_NEWCTHIN             186
#define IDD_DIALOG_MEETINGRECORD        188
#define IDB_BITMAP1                     191
#define IDC_COMBO_USER                  1000
#define IDC_EDIT_PASSWORD               1001
#define IDC_BUTTON_ADD                  1002
#define IDC_BUTTON_DELETE               1003
#define IDC_BUTTON_CANCEL               1004
#define IDC_LIST_USERLIST               1005
#define IDC_EDIT_USERNAME               1006
#define IDC_EDIT_CONFIRM                1008
#define IDC_CHECK_AUTHORITY             1009
#define IDC_STATIC_ADD                  1010
#define IDC_STATIC_INFORMATION          1011
#define IDC_EDIT_DATA                   1012
#define IDC_EDIT_DESCRIPTION            1013
#define IDC_LIST_NATIONINFORMATION      1016
#define IDC_LIST_POSITIONINFORMATON     1019
#define IDC_LIST_EDUCATIONDEGREE        1022
#define IDC_LIST_POLITICALSTATUS        1025
#define IDC_LIST_DEPARTMENTSECTION      1028
#define IDC_LIST_WAGELEVEL              1031
#define IDC_LIST_TECHNICALPOST          1034
#define IDC_LIST_ADMINISTRATIVEPOST     1037
#define IDC_EDIT_CODE                   1038
#define IDC_EDIT_LOCATION               1039
#define IDC_EDIT_SETTING                1040
#define IDC_EDIT_TEACHING               1041
#define IDC_EDIT_RESEARCHING            1042
#define IDC_EDIT_STUDENT                1043
#define IDC_COMBO_LEADER                1044
#define IDC_COMBO_NAME                  1045
#define IDC_BUTTON_SAVE                 1047
#define IDC_BUTTON_UPDATE               1048
#define IDC_COMBO_CONDITION             1050
#define IDC_EDIT_CONTENT                1051
#define IDC_BUTTON_SEARCH               1052
#define IDC_LIST_DEPARTMENT             1053
#define IDC_EDIT_RULE                   1057
#define IDC_LIST_SECTION                1067
#define IDC_EDIT_DUTY                   1073
#define IDC_LIST_AUXILIARY              1081
#define IDC_EDIT_REGULATION             1085
#define IDC_LIST_APPENDANT              1095
#define IDC_EDIT_FRUIT                  1099
#define IDC_LIST_FULLTIME               1109
#define IDC_EDIT2                       1111
#define IDC_EDIT_NAME                   1111
#define IDC_EDIT_DEPARTMENT             1111
#define IDC_EDIT_UNIT                   1111
#define IDC_EDIT_DREASON                1111
#define IDC_EDIT_PUBLICATION            1111
#define IDC_EDIT_HOST                   1111
#define IDC_EDIT_COURSE                 1111
#define IDC_EDIT_WRITER                 1111
#define IDC_COMBO_SEX                   1112
#define IDC_DATETIMEPICKER_BIRTH        1114
#define IDC_COMBO_MARRYIAGE             1115
#define IDC_EDIT3                       1116
#define IDC_EDIT_AGE                    1116
#define IDC_EDIT_PUBTIME                1116
#define IDC_EDIT_FIRST                  1116
#define IDC_EDIT_HIRE                   1116
#define IDC_EDIT_MAJOR                  1116
#define IDC_EDIT_CLASS                  1116
#define IDC_EDIT_FPHONE                 1116
#define IDC_EDIT_HOSTUNIT               1116
#define IDC_COMBO_PARTY                 1117
#define IDC_COMBO_RACE                  1118
#define IDC_EDIT4                       1119
#define IDC_EDIT_CID                    1119
#define IDC_EDIT_TECHNICAL              1119
#define IDC_EDIT_VOLUME                 1119
#define IDC_EDIT_RANK                   1119
#define IDC_EDIT_EMPLOY                 1119
#define IDC_EDIT_PARTICIPATEUNIT        1119
#define IDC_DATETIMEPICKER_WORK         1120
#define IDC_COMBO_POST                  1121
#define IDC_EDIT_NATIVE                 1122
#define IDC_DATETIMEPICKER_ENTRY        1123
#define IDC_COMBO_SALARY                1124
#define IDC_COMBO_DEGREE                1125
#define IDC_COMBO_DEPTMENT              1126
#define IDC_COMBO_TECHNICAL             1127
#define IDC_COMBO_JOB                   1128
#define IDC_EDIT_OPHONE                 1129
#define IDC_EDIT_MPHONE                 1130
#define IDC_EDIT_EMAIL                  1131
#define IDC_EDIT_UNIVERSITY             1132
#define IDC_EDIT_SUBJECT                1133
#define IDC_DATETIMEPICKER_GRADUAGE     1135
#define IDC_EDIT_ADDRESS                1136
#define IDC_LIST_FAMILY                 1137
#define IDC_EDIT_RELATION               1146
#define IDC_EDIT_COMPANY                1147
#define IDC_EDIT_PHONE                  1148
#define IDC_COMBO_POLITICAL             1150
#define IDC_EDIT_EDUCATION              1151
#define IDC_LIST_WORKEXPERIENCE         1156
#define IDC_DATETIMEPICKER_BEGIN        1157
#define IDC_DATETIMEPICKER_END          1158
#define IDC_COMBO_EDUCATION             1160
#define IDC_EDIT_PROVER                 1162
#define IDC_LIST_REWARDRECORD           1167
#define IDC_EDIT_TITLE                  1168
#define IDC_COMBO_SORT                  1169
#define IDC_COMBO_LEVEL                 1170
#define IDC_COMBO_CATEGORY              1171
#define IDC_DATETIMEPICKER_DATE         1172
#define IDC_LIST_DISCIPLINEPUNISH       1177
#define IDC_COMBO_PERIOD                1179
#define IDC_EDIT_PREASON                1180
#define IDC_DATETIMEPICKER_PDATE        1181
#define IDC_DATETIMEPICKER_DDATE        1182
#define IDC_EDIT_UNIT1                  1183
#define IDC_LIST_PAPER                  1188
#define IDC_COMBO_RANK                  1190
#define IDC_DATETIMEPICKER_PUBTIME      1191
#define IDC_EDIT_ISSUE                  1192
#define IDC_EDIT_PAGE                   1193
#define IDC_COMBO_TYPE                  1195
#define IDC_COMBO_INDEX                 1196
#define IDC_LIST_PROJECT                1201
#define IDC_COMBO_RATE                  1206
#define IDC_COMBO_STATE                 1207
#define IDC_DATETIMEPICKER_RELEASE      1208
#define IDC_EDIT_UNIT2                  1209
#define IDC_EDIT_COST                   1210
#define IDC_COMBO_LIMIT                 1211
#define IDC_LIST_TECHNICALACCESS        1218
#define IDC_COMBO_MODE                  1220
#define IDC_DATETIMEPICKER_GDATE        1221
#define IDC_DATETIMEPICKER_BDATE        1222
#define IDC_DATETIMEPICKER_EDATE        1223
#define IDC_LIST_ACADEMICEDUCATION      1228
#define IDC_COMBO_DIPLOMA               1232
#define IDC_LIST_CONTINUEEDUCATION      1238
#define IDC_COMBO_EFFECT                1242
#define IDC_EDIT_HOUR                   1244
#define IDC_LIST_CLASSTEACHING          1249
#define IDC_EDIT_ANNUAL                 1250
#define IDC_COMBO_SEMESTER              1251
#define IDC_COMBO_OBJECT                1254
#define IDC_COMBO_CONTENT               1261
#define IDC_LIST_BROWSE                 1264
#define IDC_TAB_BROWSE                  1265
#define IDC_COMBO_NATION                1273
#define IDC_COMBO_MARRIAGE              1274
#define IDC_COMBO_UNIT                  1279
#define IDC_COMBO_POSITION              1280
#define IDC_LIST_SEARCH                 1281
#define IDC_SELECTION                   1283
#define IDC_RESULT                      1284
#define IDC_EDIT_CONTEXT                1294
#define IDC_LIST_NOTES                  1295
#define IDC_LIST_THIN                   1296
#define IDC_BUTTON_VIEW                 1297
#define IDC_EDIT_SHORT                  1307
#define IDC_EDIT_QQ                     1308
#define IDC_EDIT_WECHAT                 1309
#define IDC_EDIT_REMARK                 1312
#define IDC_EDIT_WRITER1                1323
#define IDC_EDIT_DETAILS                1327
#define IDC_LIST_MEETING                1328
#define ID_SYS_USERSETTING              32771
#define ID_SYS_DBBACKUP                 32772
#define ID_SYS_DBRECOVER                32773
#define ID_SYS_RELOAD                   32774
#define ID_SYS_EXIT                     32775
#define ID_INF_NATION                   32776
#define ID_INF_POSITION                 32777
#define ID_INF_EDUCATION                32778
#define ID_INF_POLITICAL                32779
#define ID_INF_DEPT                     32780
#define ID_INF_WAGE                     32781
#define ID_INF_TECHNICAL                32782
#define ID_INF_ADMIN                    32783
#define ID_ORG_DEPT                     32784
#define ID_ORG_SECTION                  32785
#define ID_ORG_AUXILIARY                32786
#define ID_ORG_APPENDANT                32787
#define ID_ORG_FULLTIME                 32788
#define ID_HUMAN_BROWSE                 32789
#define ID_HUMAN_QUERY                  32790
#define ID_HUMAN_STATISTICS             32791
#define ID_TOOL_NOTES                   32792
#define ID_TOOL_CONTACTS                32793
#define ID_TOOL_MEETING                 32794
#define ID_HELP_ABOUT                   32795
#define ID_HELP_DOCUMENT                32796
#define ID_INDICATOR_CLOCK              61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1329
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
